myblog1/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

myblog1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

myblog1/app/models/friend.rb
class Friend < ApplicationRecord
end

myblog1/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

myblog1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

myblog1/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Đã khởi tạo thành công 1 người bạn mới" }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Đã cập nhật thành công" }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Đã xóa thành công" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:Ho_va_ten, :Email, :Phone, :Sinh_nhat)
    end
end

myblog1/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

myblog1/app/helpers/application_helper.rb
module ApplicationHelper
end

myblog1/app/helpers/friends_helper.rb
module FriendsHelper
end

myblog1/app/helpers/home_helper.rb
module HomeHelper
end

myblog1/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :Ho_va_ten, class:"form-control", placeholder:"Họ và tên" %>
    <br>
  </div>

  <div class="field form-group">
    <%= form.text_field :Email, class:"form-control", placeholder:"Email" %>
    <br>
  </div>

  <div class="field form-group">
    <%= form.text_field :Phone, class:"form-control", placeholder:"Số điện thoại" %>
    <br>
  </div>

  <div class="field form-group">
    <%= form.date_field :Sinh_nhat, class:"form-control", placeholder:"Ngày tháng năm sinh" %>
    <br>
  </div>

  <div class="submit">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

myblog1/app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>Họ và tên:</strong>
    <%= friend.Ho_va_ten %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.Email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.Phone %>
  </p>

  <p>
    <strong>Sinh nhật:</strong>
    <%= friend.Sinh_nhat %>
  </p>

</div>

myblog1/app/views/friends/edit.html.erb
<h1>Chỉnh sửa thông tin</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Trở lại thông tin bạn này", @friend, class:"btn btn-secondary" %>
</div>

myblog1/app/views/friends/index.html.erb
<h1>
  <center>DANH SÁCH BẠN BÈ</center>
</h1>

<table class="table table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Họ và tên</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Sinh nhật</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.Ho_va_ten %></td>
        <td><%= friend.Email %></td>
        <td><%= friend.Phone %></td>
        <td><%= friend.Sinh_nhat %></td>
        <td><%= link_to "Xem thông tin", friend, class:"btn btn-primary" %></td>
    <% end %>
  </tbody>
</table>
<%= link_to "Thêm bạn mới", new_friend_path, class:"btn btn-secondary" %>

myblog1/app/views/friends/new.html.erb
<h1>Thêm bạn mới</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Trở lại danh sách bạn", friends_path, class:"btn btn-dark" %>
</div>

myblog1/app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Sửa thông tin bạn này", edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to "Trở lại danh sách bạn bè", friends_path, class:"btn btn-dark" %>

  <%= button_to "Xóa bạn này ra khỏi danh sách", @friend, method: :delete %>
</div>

myblog1/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Myblog1', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About me', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Friends List', friends_path, class:"nav-link" %>
        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add friend', new_friend_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit your profile', edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

myblog1/app/views/home/about.html.erb
<h1>Thông tin về tôi</h1>
<p>
    Họ và tên: Đặng Phước Sang
    <br>
    Sinh nhật: 12/01/2003
    <br>
    Đã tốt nghiệp THPT Chuyên Bến Tre
    <br>
    Đang học tại Đại học Công nghệ Thông tin (UIT)
</p>

myblog1/app/views/home/index.html.erb
<h1>
    <center>Chào mừng đến với Blog của Phước Sang</center>
</h1>
<p>Đây là webpage đầu tiên của Sang, sử dụng Ruby on Rails</p>

myblog1/app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

myblog1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Myblog1</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container">
      <% if notice %>
        <%= render "layouts/alert" %>
      <% end %>
      <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </div>
  </body>
</html>